name: build and push to dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_image_and_push_to_registry:
    name: Push image to registry after building
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: har130798/colfe:latest